#!/usr/bin/env python3
"""
Storage Manager Module - Saves code to files and manages project structure
"""

import os
import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Optional
import subprocess


class StorageManager:
    """Manages file storage and project structure"""
    
    def __init__(self, base_dir: str = "~/ai-projects"):
        """
        Initialize storage manager
        
        Args:
            base_dir: Base directory for all projects
        """
        self.base_dir = Path(base_dir).expanduser()
        self.base_dir.mkdir(parents=True, exist_ok=True)
        
    def save(self, code: str, filename: str, language: str, 
             task: str, model: str = "qwen-coder-32b") -> Dict[str, str]:
        """
        Save generated code to file with metadata
        
        Args:
            code: Source code
            filename: Filename (e.g., "scrape_hn.py")
            language: Programming language
            task: Original task description
            model: LLM model used
            
        Returns:
            Dict with 'filepath', 'project_dir', 'readme_path'
        """
        # Create project name from filename
        project_name = filename.rsplit('.', 1)[0].replace('_', '-')
        
        # Create project directory
        project_dir = self.base_dir / project_name
        project_dir.mkdir(parents=True, exist_ok=True)
        
        print(f"📁 Creating project: {project_name}")
        
        # Save code file
        code_path = project_dir / filename
        code_path.write_text(code)
        print(f"✅ Saved code: {code_path}")
        
        # Make executable if shell script
        if language in ['bash', 'shell']:
            os.chmod(code_path, 0o755)
            print(f"✅ Made executable: {filename}")
        
        # Create README
        readme_path = self._create_readme(
            project_dir, 
            project_name, 
            filename, 
            language, 
            task
        )
        
        # Save metadata
        metadata_path = self._save_metadata(
            project_dir,
            filename,
            language,
            task,
            model
        )
        
        # Initialize git
        self._init_git(project_dir, filename)
        
        return {
            'filepath': str(code_path),
            'project_dir': str(project_dir),
            'readme_path': str(readme_path),
            'metadata_path': str(metadata_path)
        }
    
    def _create_readme(self, project_dir: Path, project_name: str,
                       filename: str, language: str, task: str) -> Path:
        """Create README.md for the project"""
        
        # Determine how to run the code
        if language == 'python':
            run_command = f"python3 {filename}"
        elif language in ['javascript', 'typescript']:
            run_command = f"node {filename}"
        elif language in ['bash', 'shell']:
            run_command = f"./{filename}"
        else:
            run_command = f"# See language documentation for {language}"
        
        readme_content = f"""# {project_name}

**Generated by Einstein AI Coding Agent**

## Task
{task}

## Language
{language}

## Usage

```bash
{run_command}
```

## File
- `{filename}` - Main script

## Generated
{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Notes
This code was generated by AI. Please review before using in production.
"""
        
        readme_path = project_dir / 'README.md'
        readme_path.write_text(readme_content)
        print(f"✅ Created README: {readme_path}")
        
        return readme_path
    
    def _save_metadata(self, project_dir: Path, filename: str,
                       language: str, task: str, model: str) -> Path:
        """Save metadata about the generation"""
        
        metadata = {
            'filename': filename,
            'language': language,
            'task': task,
            'model': model,
            'timestamp': datetime.now().isoformat(),
            'generator': 'einstein-ai-coding-agent',
            'version': '0.1.0-prototype'
        }
        
        metadata_path = project_dir / '.metadata.json'
        metadata_path.write_text(json.dumps(metadata, indent=2))
        print(f"✅ Saved metadata: {metadata_path}")
        
        return metadata_path
    
    def _init_git(self, project_dir: Path, filename: str) -> bool:
        """Initialize git repository and create initial commit"""
        
        try:
            # Check if git is available
            result = subprocess.run(
                ['git', '--version'],
                capture_output=True,
                timeout=5
            )
            
            if result.returncode != 0:
                print("⚠️  Git not available, skipping repository init")
                return False
            
            # Initialize git
            subprocess.run(
                ['git', 'init'],
                cwd=project_dir,
                capture_output=True,
                timeout=5
            )
            
            # Add .gitignore
            gitignore_path = project_dir / '.gitignore'
            gitignore_content = """# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
env/
venv/
ENV/

# Node
node_modules/
npm-debug.log
yarn-error.log

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
"""
            gitignore_path.write_text(gitignore_content)
            
            # Add all files
            subprocess.run(
                ['git', 'add', '.'],
                cwd=project_dir,
                capture_output=True,
                timeout=5
            )
            
            # Create initial commit
            commit_msg = f"Initial commit: {filename}\n\nGenerated by Einstein AI Coding Agent"
            subprocess.run(
                ['git', 'commit', '-m', commit_msg],
                cwd=project_dir,
                capture_output=True,
                timeout=5
            )
            
            print(f"✅ Initialized git repository")
            return True
            
        except Exception as e:
            print(f"⚠️  Git init failed: {e}")
            return False
    
    def list_projects(self) -> list:
        """List all projects in the base directory"""
        
        if not self.base_dir.exists():
            return []
        
        projects = []
        for item in self.base_dir.iterdir():
            if item.is_dir():
                # Load metadata if available
                metadata_path = item / '.metadata.json'
                if metadata_path.exists():
                    try:
                        metadata = json.loads(metadata_path.read_text())
                        projects.append({
                            'name': item.name,
                            'path': str(item),
                            'metadata': metadata
                        })
                    except:
                        projects.append({
                            'name': item.name,
                            'path': str(item),
                            'metadata': None
                        })
                else:
                    projects.append({
                        'name': item.name,
                        'path': str(item),
                        'metadata': None
                    })
        
        return sorted(projects, key=lambda x: x['name'])


def main():
    """Test the storage manager"""
    print("Storage Manager Test")
    print("=" * 50)
    
    manager = StorageManager()
    
    # Test saving a Python script
    test_code = '''"""
Simple test script
"""

def main():
    print("Hello from generated code!")
    print("This is a test")

if __name__ == "__main__":
    main()
'''
    
    result = manager.save(
        code=test_code,
        filename="test_script.py",
        language="python",
        task="print hello world test message",
        model="qwen-coder-32b"
    )
    
    print("\n" + "="*50)
    print("Saved files:")
    for key, value in result.items():
        print(f"  {key}: {value}")
    
    # List all projects
    print("\n" + "="*50)
    print("All projects:")
    projects = manager.list_projects()
    for project in projects:
        print(f"\n  📁 {project['name']}")
        print(f"     Path: {project['path']}")
        if project['metadata']:
            print(f"     Task: {project['metadata'].get('task', 'N/A')}")
            print(f"     Language: {project['metadata'].get('language', 'N/A')}")
            print(f"     Created: {project['metadata'].get('timestamp', 'N/A')}")


if __name__ == "__main__":
    main()
